---
title: "Untitled"
author: "Eric Knudson"
date: "1/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
google_key = as.character(read.delim("my_key.txt", header = FALSE)[1,])
```

```{r}
km = kmeans(kc[c("lat","long")],50)
kc$neighborhood = as.factor(km$cluster)
sample_index = sort(sample(seq_len(nrow(kc)), replace = FALSE, size = 1000))
sample = kc[sample_index,]
map = get_map(location='seattle', zoom=10, maptype = "terrain", source='google', color='bw')
ggmap(map) + geom_point(data = sample, aes(x=long, y=lat, color=neighborhood))
```

```{r}
map = get_map(location='seattle', zoom=10, maptype = "terrain", source='google', color='bw')
ggmap(map) + geom_point(data = sample, aes(x=long, y=lat, color=zipcode))
```


```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center', fig.height=3, fig.width=8}
library("ggmap")
register_google(key = google_key)

qmplot(long, lat, data = kc, source="google", maptype="terrain", geom = "blank", zoom = 9, extent = "panel", xlim = c(-122.5,-121.8), ylim = c(47.2,47.8)) + 
  geom_density_2d(color = "#000000")

```

```{r}
hist(kc$lat)
```


```{r}
library(ggmap)
register_google(key = google_key)
seattle <- get_map(location = "bellevue", zoom = 11)
ggmap(seattle)+ 
  geom_density2d(data = kc, aes(x = long, y = lat), size = 0.3) + 
  stat_density2d(data = kc, 
                 aes(x = long, y = lat, fill = ..level.., alpha = ..level..), size = 0.01, 
                 bins = 16, geom = "polygon") + scale_fill_gradient(low = "green", high = "red") + 
  scale_alpha(range = c(0, 0.3), guide = FALSE)
```

```{r}
      library("ggmap")
      register_google(key = google_key)
      sample_index = sort(sample(seq_len(nrow(kingcounty)), replace = FALSE, size = floor(nrow(kingcounty)*.1)))
      sample = kingcounty[sample_index,]
      qmplot(long, lat, data = sample, source="google", maptype="terrain", geom = "blank", zoom = 9, extent = "panel") + 
        geom_density_2d(color = "#000000")
```